export const INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS';
export type INSUFFICIENT_FUNDS = typeof INSUFFICIENT_FUNDS;

export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
export type SERVICE_UNAVAILABLE = typeof SERVICE_UNAVAILABLE;